---
  - namespace: io
    type: MVP
    scope:
    - /
  - namespace: raft
    type: MVP
    scope:
    - /
  - namespace: merkleTools
    type: MVP
    scope:
        - /
  - namespace: soundcheckbox
    type: MVP
    scope:
    - /
    - /soundcheckbox.github.io.git
  - namespace: presets
    type: MVP
    scope:
    -
  - namespace: save
    type: MVP
    scope:
    - /
  - namespace: interface
    type: MVP
    scope:
    - /
  - namespace: group
    type: MVP
    scope:
    - /
  - namespace: img
    type: MVP
    scope:
    - /
  - namespace: soundStorage
    type: MVP
    scope:
    - /
  - namespace: blockchain
    type: MVP
    scope:
    - /
