---
  - namespace: io
    type: MVP
    scope:
    - /
  - namespace: database
    type: MVP
    scope:
    - /
  - namespace: merkleTools
    type: MVP
    scope:
    - /
  - namespace: consensus
    type: MVP
    scope:
    - /
  - namespace: soundcheckbox
    type: MVP
    scope:
    - /
    - /soundcheckbox.github.io.git
    - /editor
  - namespace: presets
    type: MVP
    scope:
    - /
  - namespace: radio
    type: MVP
    scope:
    - /
  - namespace: fileSystem
    type: MVP
    scope:
    - /
  - namespace: auction
    type: MVP
    scope:
    - /
  - namespace: booking
    type: spa
    scope:
    - /docs
  - namespace: warehouse
    type: MVP
    scope:
    - /docs
  - namespace: blockchain
    type: MVP
    scope:
    - /
