---
  - page: io
    dir:
    - /
  - page: ipfs
    dir:
    - /docs
  - page: soundcheckbox
    dir:
    - /docs
  - page: presets
    dir:
    -
  - page: save
    dir:
    -
  - page: interface
    dir:
    -
  - page: group
    dir:
    -
  - page: img
    dir:
    -
  - page: soundStorage
    dir:
    -
  - page: blockchain
    dir:
    - /docs
