---
  - page: io
    dir:
    - /docs
    router:
        - orbitdb
  - page: soundcheckbox
    dir:
    - /docs
  - page: presets
    dir:
    -
  - page: save
    dir:
    -
  - page: interface
    dir:
    -
  - page: group
    dir:
    -
  - page: img
    dir:
    -
  - page: soundStorage
    dir:
    -
